FROM ubuntu:22.04
ADD https://factorio.com/get-download/1.1.110/headless/linux64 /tmp/factorio.tar.xz
RUN apt-get update && apt-get install -y xz-utils && \
    tar -xf /tmp/factorio.tar.xz -C /opt && \
    rm /tmp/factorio.tar.xz && \
    apt-get remove -y xz-utils && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /opt/factorio

