name: Build Workflow

on: push

jobs:
  CICD:
    name: CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1.3.0
      - name: Install Dependencies
        run: npm ci
      - name: Run Test Scripts
        run: npm test
      - name: Publish to Docker Hub
        if: startsWith(github.ref,'refs/tags/')
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          VERSION="$(node -e "console.log(require('./package.json').version)")"
          APPNAME="$(node -e "console.log(require('./package.json').name.substring(1))")"
          docker build -t $APPNAME:latest -t $APPNAME:$VERSION .
          docker push $APPNAME:latest
          docker push $APPNAME:$VERSION
