cargo-features = ["per-package-target"]
[package]
default-target = "wasm32-unknown-unknown"
edition = "2021"
name = "covert_c2_ping_web"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
