[package]
name = "async_pipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.72"
nix = "0.26.2"
tokio = { version = "1.30.0", features = ["full"] }
