name: Build Workflow

on: push

jobs:
  CICD:
    name: CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1.3.0
      - name: Install Dependencies
        run: npm ci
      - name: Run Test Scripts
        run: npm test
      - name: Publish to Docker Hub
        if: github.ref == 'refs/heads/master'
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          VERSION="$(node -e "console.log(require('./package.json').version)")"
          APPNAME="$(node -e "console.log(require('./package.json').name.substring(1))")"
          docker build -t $APPNAME:latest -t $APPNAME:$VERSION .
          docker push $APPNAME:latest
          docker push $APPNAME:$VERSION
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: "init"
          tf_actions_comment: false
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: "plan"
          tf_actions_comment: false
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/master'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: "apply"
          tf_actions_comment: false
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
