apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: v2.5.0
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
