apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: v0.16.0
      helm:
        values: |
          frr-k8s:
            prometheus:
              serviceMonitor:
                enabled: false
  destination:
    server: https://kubernetes.default.svc
