[package]
edition = "2021"
name = "java_decompiler"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.1"
nom = "7.1.3"

[dev-dependencies]
colored = "2.0.0"
