cargo-features = ["profile-rustflags"]
[workspace]
members = ["weezie-core"]

[profile.shellcode]
inherits = "release"
lto = true
opt-level = "z"
panic = "abort"
rustflags = ["-C", "link-args=-nostartfiles","-C","strip=symbols"]
