[package]
name = "tls_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
rcgen = "0.13.1"
ring = { version = "0.17.8", features = ["std"] }
rustls = { version = "0.23.19", features = ["ring"] }
time = "0.3.36"
tokio = { version = "1.41.1", features = ["full"] }
