[package]
name = "covert_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
covert_client = "0.1.5"
covert_common = "0.1.3"
covert_server = "0.1.4"
