[workspace]
members = ["covert_c2_ping_server", "covert_c2_ping_client", "covert_c2_ping_common", "covert_c2_ping_web"]

[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
lto = true
opt-level = "s"
overflow-checks = false
panic = "abort"
strip = "symbols"
