[package]
name = "trace_conn"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
clap = { version = "4.5.17", features = ["derive"] }
libc = "0.2.158"
tokio = { version = "1.40.0", features = ["full"] }
