apiVersion: v2
name: npc
description: NPC Infrastructure Helm Chart
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - npc
  - vmware
  - controller
  - matrix
maintainers:
  - name: hattmo
